//This file acts as a contract between the client and server,
// describing both the structure of the data and the remote procedure calls (RPCs)
// they use to communicate.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: grpc/auction.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionServer_Bid_FullMethodName    = "/grpc.AuctionServer/Bid"
	AuctionServer_Result_FullMethodName = "/grpc.AuctionServer/Result"
)

// AuctionServerClient is the client API for AuctionServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionServerClient interface {
	// Method:  bid
	// Inputs:  amount (an int)
	// Outputs: ack
	// Comment: given a bid, returns an outcome among {fail, success or exception}
	Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error)
	// Method:  result
	// Inputs:  void
	// Outputs: outcome
	// Comment: if the auction is over, it returns the result, else highest bid.
	Result(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error)
}

type auctionServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionServerClient(cc grpc.ClientConnInterface) AuctionServerClient {
	return &auctionServerClient{cc}
}

func (c *auctionServerClient) Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AuctionServer_Bid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServerClient) Result(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, AuctionServer_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionServerServer is the server API for AuctionServer service.
// All implementations must embed UnimplementedAuctionServerServer
// for forward compatibility.
type AuctionServerServer interface {
	// Method:  bid
	// Inputs:  amount (an int)
	// Outputs: ack
	// Comment: given a bid, returns an outcome among {fail, success or exception}
	Bid(context.Context, *Amount) (*Ack, error)
	// Method:  result
	// Inputs:  void
	// Outputs: outcome
	// Comment: if the auction is over, it returns the result, else highest bid.
	Result(context.Context, *Empty) (*Outcome, error)
	mustEmbedUnimplementedAuctionServerServer()
}

// UnimplementedAuctionServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionServerServer struct{}

func (UnimplementedAuctionServerServer) Bid(context.Context, *Amount) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionServerServer) Result(context.Context, *Empty) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionServerServer) mustEmbedUnimplementedAuctionServerServer() {}
func (UnimplementedAuctionServerServer) testEmbeddedByValue()                       {}

// UnsafeAuctionServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServerServer will
// result in compilation errors.
type UnsafeAuctionServerServer interface {
	mustEmbedUnimplementedAuctionServerServer()
}

func RegisterAuctionServerServer(s grpc.ServiceRegistrar, srv AuctionServerServer) {
	// If the following call pancis, it indicates UnimplementedAuctionServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionServer_ServiceDesc, srv)
}

func _AuctionServer_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServerServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionServer_Bid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServerServer).Bid(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionServer_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServerServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionServer_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServerServer).Result(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionServer_ServiceDesc is the grpc.ServiceDesc for AuctionServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.AuctionServer",
	HandlerType: (*AuctionServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bid",
			Handler:    _AuctionServer_Bid_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _AuctionServer_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/auction.proto",
}
